jobs:
- job: component_detection
  displayName: Python Build
  dependsOn: build_identity
  strategy:
    matrix:
      linux:
        os: "ubuntu-latest"
      macos:
        os: "macos-latest"
      windows:
        os: "windows-latest"
  pool:
    vmImage: $(os)
  steps:
    - task: ComponentGovernanceComponentDetection@0
